# Generated by Django 4.2.15 on 2024-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='images/category/default.jpg', null=True, upload_to='images/category', verbose_name='Icon'),
        ),
    ]
