# Generated by Django 4.2.15 on 2024-08-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Please enter the ID without @', max_length=256, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.FloatField(default=32.646849, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.FloatField(default=51.667791, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_closing',
            field=models.TextField(default='', verbose_name='Opening and Closing Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, help_text='Please enter the ID without @', max_length=256, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(help_text='Example: +98913xxxxxxx', max_length=32, verbose_name='Phone'),
        ),
    ]
