# Generated by Django 4.2.15 on 2024-08-27 07:41

import apps.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sitesettings_instagram_sitesettings_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, default='images/category/default.jpg', null=True, upload_to='images/category', validators=[apps.api.validators.icon_validator], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='latitude',
            field=models.FloatField(default=32.7024361, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='longitude',
            field=models.FloatField(default=51.6777003, verbose_name='Longitude'),
        ),
    ]
